Repository tryber/sd-010-a-project-trivia-react-redux, pull requests merged in 2021-06, with the labels that each got.

#15 [Main group 30] - feat: req-1 - starting
  package-lock.json
  src/App.js
Labels: grupo 30

#9 [GROUP 5] feat: initial commit
  package-lock.json
  package.json
  src/App.js
  src/index.js
  src/pages/Login.jsx
  src/redux/actions/index.js
  src/redux/reducers/index.js
  src/redux/store/index.js
Labels: code review

#48 [ requisito 1 ] Group2
  package-lock.json
  package.json
  src/App.js
  src/App.test.js
  src/actions/index.js
  src/components/Header.js
  src/components/Multiple.js
  src/components/QuestionText.js
  src/components/TrueFalse.js
  src/index.js
  src/pages/Feedback.js
  src/pages/GamePage.js
  src/pages/Login.js
  src/pages/Ranking.js
  src/reducer/index.js
  src/reducer/userReducer.js
  src/store/store.js
Labels: code review

#52 [Group 19] - Requisito 1
  package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/App.css
  src/App.js
  src/App.test.js
  src/index.css
  src/index.js
  src/pages/Login.jsx
  src/redux/actions/index.js
  src/redux/reducer/index.js
  src/redux/reducer/user.js
  src/redux/store/index.js
  src/utils/functions.js
Labels: code review

#64 [Group 8] requirement 01
  package-lock.json
  src/App.js
  src/pages/Login.js
Labels: code review

#60 [Group 5] Implement req 2
  package-lock.json
  src/App.js
  src/pages/Game.jsx
  src/pages/Login.jsx
Labels: code review

#94 [Main group 5] req4
  README.md
  package-lock.json
  src/components/Header.jsx
  src/pages/Game.jsx
  src/pages/Login.jsx
  src/redux/actions/index.js
  src/redux/reducers/index.js
  src/redux/reducers/login.js
Labels: code review

#115 Main group 30 req1 a 4
  src/components/routes.js
  src/pages/Configuracoes.jsx
  src/pages/Jogo.jsx
  src/pages/Login.jsx
  src/redux/actions/actions.js
  src/redux/reducers/jogo.js
  src/services/triviaAPI.js
Labels: grupo 30

#107 [Main group 5] req3
  src/App.js
  src/components/Questions.jsx
  src/pages/Configuration.jsx
  src/pages/Game.jsx
  src/pages/Login.jsx
Labels: code review

#106 [Main group 5] req5
  src/components/Questions.jsx
  src/pages/Game.jsx
Labels: code review

#112 Add settings button
  package-lock.json
  src/App.js
  src/pages/GameScreen.js
  src/pages/Login.js
  src/pages/SetupScreen.js
Labels: code review

#119 [Group 19] - Requisito 2
  package-lock.json
  package.json
  src/App.js
  src/pages/Game.jsx
  src/pages/Login.jsx
  src/utils/api.js
Labels: code review

#134 [Group 19] - Requisito 4
  src/App.js
  src/components/Header.jsx
  src/pages/Game.jsx
  src/pages/Login.jsx
  src/redux/actions/index.js
  src/redux/reducer/user.js
Labels: code review

#140 [Group 19] - Requisito 3
  src/App.js
  src/pages/Login.jsx
  src/pages/Settings.jsx
Labels: code review

#135 [Group 19] - Req5
  package-lock.json
  package.json
  src/components/Question.jsx
  src/pages/Game.jsx
  src/utils/triviaApi.js
Labels: code review

#81 [Requisito 2] unfinished
  package-lock.json
  package.json
  src/App.css
  src/App.js
  src/actions/index.js
  src/index.js
  src/pages/Game.js
  src/pages/Login.js
  src/reducers/index.js
  src/reducers/loginReduce.js
  src/services/datasApi.js
  src/store/index.js
Labels: code review

#110 Group 6 - Req 04
  package-lock.json
  package.json
  src/components/Header.js
  src/components/Routers.js
  src/pages/Game.js
  src/pages/Login.js
  src/redux/actions/index.js
  src/redux/reducers/playerReducer.js
Labels: code review

#156 feat: implement req 6
  src/components/Questions.jsx
Labels: code review

#167 [Group 19] - Req7
  src/components/Question.jsx
  src/styles/question.css
Labels: code review

#197 [Main group 5] req7
  src/components/Header.jsx
  src/components/Questions.jsx
Labels: code review

#183 [ Group 33 ] Req 1 and 3
  package-lock.json
  package.json
  src/App.js
  src/actions/index.js
  src/index.js
  src/pages/Feedback.jsx
  src/pages/Login.jsx
  src/pages/NotFound.jsx
  src/pages/Questions.jsx
  src/pages/Ranking.jsx
  src/pages/Settings.jsx
  src/reducers/index.js
  src/reducers/player.js
  src/store/index.js
Labels: code review

#206 [ GROUP 5] group5 req8
  src/App.test.js
  src/components/Header.jsx
  src/components/Questions.jsx
  src/components/Timer.jsx
  src/redux/actions/index.js
  src/redux/reducers/disableButton.js
  src/redux/reducers/index.js
Labels: code review

#211 [Req 10] - Grupo 2
  src/App.css
  src/pages/GamePage.js
  src/pages/Login.js
Labels: code review

#224 [Main group 30] req6 e req7
  package-lock.json
  src/components/Alternatives.css
  src/components/Alternatives.jsx
  src/components/Questions.jsx
  src/components/TrueFalse.jsx
Labels: grupo 30

#226 [Main group 30] req67
  src/components/Alternatives.css
  src/components/Questions.jsx
Labels: grupo 30

#228 [ Requisito 5]: Grupo 2 - ajustes - renderização aleatória das respostas
  src/pages/GamePage.js
Labels: code review

#241 Main group 11 - Requisito 16
  src/pages/Feedback.js
  src/pages/Ranking.js
Labels: code review

#194 [Group 19] - Requisito 9
  src/components/Header.jsx
  src/components/Question.jsx
  src/pages/Game.jsx
  src/pages/Login.jsx
  src/utils/functions.js
Labels: code review

#213 [Group 19] - Requisito 8
  src/components/Question.jsx
  src/pages/Game.jsx
Labels: code review

#232 [Main group 5] req10
  src/components/Questions.jsx
Labels: code review

#159 [Group 27] Requisito 13
  src/components/Timer.js
  src/pages/GamePlay.jsx
Labels: code review

#261 Main group 13 - req 1, 2, 3, 4
  package-lock.json
  package.json
  src/App.js
  src/components/Answer.js
  src/components/ButtonNext.js
  src/components/Header.js
  src/components/HeaderTriviaGame.js
  src/components/Question.js
  src/components/Timer.js
  src/helper/index.js
  src/index.js
  src/pages/Login.js
  src/pages/NotFound.js
  src/pages/Ranking.js
  src/pages/Settings.js
  src/pages/TriviaGame.js
  src/redux/action/index.js
  src/redux/reducer/index.js
  src/redux/reducer/user.js
  src/redux/store/index.js
Labels: code review

#277 fix: refactor req8
  src/components/Header.jsx
  src/components/Questions.jsx
  src/components/Timer.jsx
  src/redux/actions/index.js
  src/redux/reducers/disableButton.js
  src/redux/reducers/index.js
Labels: code review

#274 [Group 33] Req 2
  src/App.jsx
  src/actions/index.js
  src/pages/Login.jsx
  src/reducers/player.js
  src/services/api.js
Labels: code review

#219 [group 14] Incomplete requirement - error correction
  src/App.css
  src/pages/Game.js
  src/pages/Login.js
Labels: code review

#285 [Group 19] - Requisito 10
  src/components/Question.jsx
Labels: code review

#295 [Group 33] Req 4
  src/actions/index.js
  src/components/Header.jsx
  src/pages/Login.jsx
  src/pages/Questions.jsx
  src/reducers/player.js
Labels: code review

#291 [Requisito 11] - Group 2
  src/components/Button.jsx
  src/components/Loading.jsx
  src/components/Question.jsx
  src/components/QuestionText.js
  src/pages/GamePage.js
Labels: code review

#328 [Main group 5] req15
  package-lock.json
  src/App.css
  src/App.js
  src/components/Questions.jsx
  src/pages/Feedback.jsx
Labels: code review

#344 [Main group 5] - req13
  src/components/Questions.jsx
  src/pages/Feedback.jsx
  src/redux/actions/index.js
  src/redux/reducers/index.js
  src/redux/reducers/quantyAssertions.js
Labels: code review

#142 [Group 19] - Requisito 12
  README.md
  package-lock.json
  src/App.js
  src/components/Question.jsx
  src/pages/Feedback.jsx
  src/pages/Game.jsx
Labels: grupo 19

#326 [Group 33] Req 5
  src/components/Question.jsx
  src/pages/Login.jsx
  src/pages/Questions.jsx
  src/services/api.js
Labels: code review

#368 [Group 19] - Requisito 11
  src/App.js
  src/components/Question.jsx
  src/pages/Feedback.jsx
  src/pages/Game.jsx
Labels: code review, grupo 19

#377 [main group 30] feat: req10 finalizado
  src/components/Alternatives.css
  src/components/Alternatives.jsx
  src/components/Timer.jsx
Labels: grupo 30

#379 [ Group 17 ] Feat: req 10 and code refactoring
  src/actions/index.js
  src/components/Timer.js
  src/pages/Game.js
  src/pages/Login.js
  src/reducers/game.js
  src/styles/Game.css
Labels: grupo 17

#374 [Group 19] - Requisito 15
  src/pages/Feedback.jsx
Labels: code review, grupo 19

#355 [Group 19] Requisito 14
  src/pages/Feedback.jsx
Labels: code review, grupo 19

#421 Main group 16 requisito 17b
  cypress/integration/project.spec.js
  src/PAGES/Feedback.jsx
  src/PAGES/Game.jsx
  src/PAGES/Ranking.jsx
  src/REDUX/Reducers/PlayerReducer.jsx
Labels: code review

#361 [Group 19] - Requisito 16
  src/App.js
  src/components/Question.jsx
  src/pages/Feedback.jsx
  src/pages/Game.jsx
  src/pages/Ranking.jsx
Labels: code review, grupo 19

#386 [main-group-5] req 12 fix. Add span tag to receive score value
  src/components/Header.jsx
Labels: code review

#394 [Main group 5] req14
  src/components/Questions.jsx
  src/pages/Feedback.jsx
Labels: code review

#432 [Main group 30] req 12
  src/components/Alternatives.jsx
  src/components/FeedbackMsg.jsx
  src/components/FeedbackResults.jsx
  src/components/Header.jsx
  src/components/Questions.jsx
  src/components/Timer.jsx
  src/components/routes.js
  src/pages/Feedback.jsx
  src/pages/Jogo.jsx
  src/pages/Ranking.jsx
Labels: grupo 30

#439 [Group 33] Req 7 - 10
  src/App.css
  src/App.jsx
  src/components/Question.jsx
  src/pages/Questions.jsx
Labels: code review

#415 [ grupo 14 ] Feat: (req10)
  src/components/Header.js
  src/pages/Game.js
Labels: code review

#438 [Group 19] - Requisito 13
  src/App.js
  src/pages/Feedback.jsx
  src/pages/Game.jsx
  src/utils/functions.js
Labels: code review, grupo 19

#443 [Group 19] - Requisito 18
  src/pages/Ranking.jsx
Labels: code review, grupo 19

#455 feat: requirement 17 and 18, implements method restart global state
  src/actions/index.js
  src/pages/Feedback.jsx
  src/pages/Game.js
  src/pages/Login.jsx
  src/pages/Ranking.jsx
  src/reducers/apiResponse.js
  src/reducers/player.js
Labels: code review

#375 [Requisitos 8 e 9 - completos] Main Group 2
  src/actions/index.js
  src/components/Button.jsx
  src/components/Header.js
  src/components/Question.jsx
  src/components/Timer.jsx
  src/pages/GamePage.js
  src/pages/Settings.js
  src/reducer/userReducer.js
  src/services/shuffle.js
Labels: code review

#362 [Group 19] - Requisito 17
  src/App.js
  src/pages/Game.jsx
  src/pages/Ranking.jsx
  src/utils/functions.js
Labels: code review, grupo 19

#458 [Group 5] Req 17
  src/components/Header.jsx
  src/components/Questions.jsx
  src/pages/Ranking.jsx
  src/redux/actions/index.js
  src/redux/reducers/login.js
Labels: code review

#489 [Group 33] Requisitos 15 e 18
  src/pages/Feedback.jsx
  src/pages/Ranking.jsx
Labels: code review

#506 [Group 33] Req 15 and 18
  src/App.css
  src/App.jsx
  src/components/Header.jsx
  src/pages/Feedback.jsx
  src/pages/Questions.jsx
  src/pages/Ranking.jsx
Labels: code review

#509 [grupo 14] Feat: (req -11)
  src/App.js
  src/pages/Feedback.js
  src/pages/Game.js
  src/pages/Ranking.js
  src/services/datasApi.js
Labels: code review

#474 [ Tela Feedback - Reqs 12 -16 ] Group 2
  src/App.js
  src/components/Question.jsx
  src/pages/Feedback.js
  src/pages/Ranking.js
Labels: code review

#491 [Group - 18] - screen settings
  package-lock.json
  package.json
  src/actions/index.js
  src/components/LoginForm.jsx
  src/components/NextQuestion/NextQuery.jsx
  src/components/Questions.jsx
  src/pages/Game.jsx
  src/pages/Settings.jsx
  src/reducers/player.js
  src/services/fetchCategories.js
  src/styles/question.css
Labels: code review

#511 [Group 19] - Css ranking
  src/App.js
  src/global.css
  src/index.js
  src/pages/Ranking.jsx
  src/styles/ranking.css
Labels: code review, grupo 19

#448 [ Group 17 ] Feat: req 9 (incomplete)
  src/actions/index.js
  src/actions/manageQuestions.js
  src/components/Question.js
  src/components/Timer.js
  src/pages/Game.js
  src/reducers/game.js
  src/reducers/index.js
  src/reducers/questions.js
Labels: grupo 17

#530 [Group 33] Requisito 8
  src/components/Timer.jsx
  src/pages/Questions.jsx
Labels: code review

#513 [Group 19] - Css Game and Question
  public/index.html
  src/App.js
  src/components/Question.jsx
  src/global.css
  src/pages/Game.jsx
  src/styles/game.css
  src/styles/question.css
Labels: code review, grupo 19

#508 [Group 30] - Refatoração
  src/components/Alternative.jsx
  src/components/Alternatives.jsx
  src/components/FeedbackMsg.jsx
  src/components/FeedbackResults.jsx
  src/components/Header.jsx
  src/components/LoginForm.jsx
  src/components/NextQuestionBtn.jsx
  src/components/Question.jsx
  src/components/Questions.jsx
  src/components/Timer.jsx
  src/pages/Feedback.jsx
  src/pages/Jogo.jsx
  src/pages/Login.jsx
  src/redux/actions/actions.js
  src/redux/reducers/jogo.js
  src/redux/reducers/login.js
  src/redux/reducers/reducers.js
  src/redux/reducers/timer.js
  src/services/storage.js
  src/services/triviaAPI.js
Labels: grupo 30

#528 [Group33] Página Not Found
  README.md
  src/App.css
  src/erro404.jpg
  src/pages/NotFound.jsx
Labels: code review

#549 [ Group 17 ] - Req 11
  src/components/Header.js
  src/components/routes.js
  src/pages/Feedback.js
  src/pages/Game.js
  src/pages/Login.js
Labels: grupo 17

#545 [Group 33] Req 8
  package.json
  src/components/Question.jsx
  src/components/Timer.jsx
  src/pages/Questions.jsx
Labels: code review

#555 [ Group 17 ] Req 12, 13, 14 & 15
  src/actions/manageQuestions.js
  src/components/Header.js
  src/components/Question.js
  src/pages/Feedback.js
  src/pages/Game.js
  src/reducers/questions.js
Labels: grupo 17

#558 [Main group 30] - Requisito 17 / Projeto 100%!!!!
  package-lock.json
  src/components/Alternative.jsx
  src/components/Header.jsx
  src/components/NextQuestionBtn.jsx
  src/components/Question.jsx
  src/helpers/getGravatar.js
  src/helpers/storage.js
  src/pages/Login.jsx
  src/pages/Ranking.jsx
  src/redux/reducers/jogo.js
  src/services/storage.js
Labels: grupo 30

#540 [MAIN-GROUP-30] req-17 e 18
  cypress/integration/project.spec.js
  package-lock.json
  src/components/Alternative.jsx
  src/components/Header.jsx
  src/pages/Ranking.jsx
Labels: grupo 30

#562 [Group 33] Req todo o resto menos 17
  src/actions/index.js
  src/components/Question.jsx
  src/pages/Feedback.jsx
  src/pages/Questions.jsx
  src/pages/Ranking.jsx
  src/reducers/player.js
Labels: code review

#561 [Grupo 3] - Requisitos 8 e 9
  README.md
  src/pages/Game.js
  src/pages/Header.js
  src/pages/Ranking.js
Labels: Grupo 03

#560 [ Group 17 ] Feat: req 16 & 18
  src/App.js
  src/actions/index.js
  src/actions/manageQuestions.js
  src/components/Header.js
  src/components/Question.js
  src/components/routes.js
  src/pages/Feedback.js
  src/pages/Game.js
  src/pages/Ranking.js
  src/reducers/game.js
  src/reducers/player.js
  src/reducers/questions.js
Labels: grupo 17

#445 [group-26]-renzosev-req17/18
  package-lock.json
  package.json
  public/index.html
  src/App.css
  src/components/Button/index.jsx
  src/components/Countdown/index.jsx
  src/components/Countdown/styles.css
  src/components/Questions/index.jsx
  src/helper/game.js
  src/helper/localStorage.js
  src/helper/player.js
  src/helper/user.js
  src/index.css
  src/index.jsx
  src/pages/Feedback/index.jsx
  src/pages/Game.jsx
  src/pages/Game/index.jsx
  src/pages/Game/styles.css
  src/pages/Login.jsx
  src/pages/Login/index.jsx
  src/pages/Login/styles.css
  src/pages/Ranking.jsx
  src/pages/Ranking/index.jsx
  src/pages/Settings/index.jsx
  src/pages/game.css
  src/redux/actions/game/addQuestion.js
  src/redux/actions/game/addQuestionNumber.js
  src/redux/actions/game/addTime.js
  src/redux/actions/index.js
  src/redux/actions/player/addPlayer.js
  src/redux/actions/player/addScore.js
  src/redux/actions/ranking/addRanking.js
  src/redux/actions/user/addUser.js
  src/redux/reducer/game.js
  src/redux/reducer/index.js
  src/redux/reducer/ranking.js
  src/services/api.js
  src/styles/button.js
  src/styles/index.css
Labels: code review

#597 [Group33] Estilização
  package-lock.json
  package.json
  src/App.css
  src/App.jsx
  src/actions/index.js
  src/components/Header.jsx
  src/components/Question.jsx
  src/components/badge/Badge.jsx
  src/components/badge/BadgeStyle.jsx
  src/components/button/Button.jsx
  src/components/button/ButtonStyled.jsx
  src/components/input/Input.jsx
  src/components/input/InputStyled.jsx
  src/components/select/Select.jsx
  src/components/select/SelectStyled.jsx
  src/components/timer/Timer.jsx
  src/components/timer/TimerStyled.jsx
  src/const/validation.js
  src/pages/Feedback.jsx
  src/pages/Login.jsx
  src/pages/Questions.jsx
  src/pages/Settings.jsx
  src/reducers/index.js
  src/reducers/settings.js
  src/services/api.js
Labels: code review

#609 [ Timer ] - Grupo 2 - Transferindo estados locais do componente timer para estado global do redux
  package-lock.json
  package.json
  src/actions/index.js
  src/components/Question/Question.jsx
  src/components/Timer.jsx
  src/pages/GamePage.js
  src/pages/Ranking.js
  src/reducer/index.js
  src/reducer/rankingReducer.js
  src/reducer/timerReducer.js
  src/reducer/userReducer.js
Labels: code review

#632 [Group 33] Requisito 17 - Ranking
  src/actions/index.js
  src/pages/Feedback.jsx
  src/pages/Ranking.jsx
  src/reducers/index.js
  src/reducers/ranking.js
Labels: code review
